### ISSUE TITLE
Implement a multi language option

### ISSUE THREAD

**Issue by severinmenard** [stamen/fieldpapers#273]
So that contributors can translate in their own language and make the access easier for their fellow citizen that are not English speaking.
Would be good to set an easy translation platform like Transifex.

**Comment by pyrog** [comment]
I see a first version of localization done in 2009: 6f149739ab585227479d3b5ae8fcb96926c95933

What do you think of using this [Philipp15b/php-i18n](https://github.com/Philipp15b/php-i18n) ?
I suggest to use .yaml format because it is used by [transifex](http://docs.transifex.com/developer/formats/yaml#read-more), [translatewiki.net](http://translatewiki.net)

Or using gettext api, see: http://codesamplez.com/programming/php-i18n-internationalization-tutorial supported by [transifex](http://docs.transifex.com/developer/formats/yaml#read-more), [translatewiki.net](http://translatewiki.net) and also by [zanata](http://zanata.org)

With **.yaml** or **.po** files, you could also simply edit files with basic editor.

**Comment by mojodna** [comment]
gettext was my first instinct, but I haven't looked at the various options in a while, so this is helpful.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
